### ISSUE TITLE
Fix photos url when project is at production

### ISSUE THREAD

**Issue by Katsu08** [Azordev/sencico#100]
Para acceder a las imágenes desde el servidor (en producción), no es necesario colocar "public/storage" en la ruta de los archivos. ¿Por qué?. Porque cuando estás en producción y haces el build, ya estás en la carpeta public, solo debes acceder a storage, así que con colocar `linkdelapi.com:9999/` ya es suficiente

**Comment by e-azocar** [comment]
pero el storage ya viene,entonces sería solo /storage/...?

**Comment by Katsu08** [comment]
> pero el storage ya viene,entonces sería solo /storage/...?

Si exacto, como el storage ya viene solo con colocar el enlace del api es suficiente. Ahí cuando se concatene lo que nos trae la base de datos, eso viene similar a: "/storage/images/products..." por lo que quedaría como: "api.enlace.com/storage/images/products"
@e-azocar
