### ISSUE TITLE
Move footer data to JSON and import to reduce file size

### ISSUE THREAD

**Issue by Katsu08** [Azordev/sencico#6]
For easily add-remove footer nav links, it's good to have these in a JSON and resort this file.

Please move the links data to a JSON and use it on Footer file

https://github.com/Azordev/sencico/blob/dae13f4e65d63dcf600e4f7166636bd5c1000a2a/src/components/Footer.jsx

**Comment by Israel-Laguan** [comment]
Not needed now, will be on stale in the meantime
