### ISSUE TITLE
Component my downloads with text on post

### ISSUE THREAD

**Issue by angelik0828** [Azordev/sencico#71]
When entering small screens a text is superimposed on the component user login
![image (2)](https://user-images.githubusercontent.com/4030477/147295017-43563598-9d63-4518-9097-a313363c0b0e.png)
.

**Comment by Katsu08** [comment]
Bug already fixed on #70 . Thanks! 
![imagen](https://user-images.githubusercontent.com/66505715/147354242-3d1648ae-bbc5-49f7-8d9c-bce0b5f8fe9a.png)
